# Site settings
name: Wiaa
title: Wiaa
locale: en_US
logo: #site-logo.png
search: true
description: >
  Blog about Clojure and various thoughts.
url:

# Jekyll configuration
permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

exclude: ["drafts/", "exclude/", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Olivier Barbeau
  avatar: 306801.jpg
  email: olivier.barbeau@gmail.com
  disqus-shortname:
  twitter: obarbeau
  facebook: #username
  github: obarbeau
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-60157931-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
